
create table Khoa
(
MaKHOA char(2) primary key,
TENKHOA nvarchar(20)
)
Create table MONHOC
(
MAMH CHAR(2)PRIMARY KEY,
TENMH NVARCHAR(30),
SOTIET TINYINT
)
CREATE TABLE SINHVIEN
(MASV CHAR(3)primary key,
HOSV NVARCHAR(30),
TENSV NVARCHAR(10),
PHAI BIT,
NGAYSINH DATE,
NOISINH  NVARCHAR(25),
MAKH  CHAR(2)CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY REFERENCES KHOA(MaKHOA),
HOCBONG FLOAT)
create table KETQUA
(
	MaSV char(3)CONSTRAINT FK_KETQUA_SINHVIEN FOREIGN KEY REFERENCES SINHVIEN(MASV),
	MaMH char (2) CONSTRAINT FK_KETQUA_MONHOC FOREIGN KEY REFERENCES MONHOC(MAMH),
	LANTHI tinyint,
	Diem decimal(4,2),
	constraint PK_ketqua primary key (MaSV,MaMH,LANTHI)
	)
ALTER TABLE SINHVIEN ADD
	CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY (MAKH) REFERENCES KHOA(MaKHOA)
ALTER TABLE KETQUA ADD
	CONSTRAINT FK_KETQUA_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT FK_KETQUA_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
alter table SINHVIEN DROP FK_SINHVIEN_KHOA
ALTER TABLE KETQUA DROP FK_KETQUA_MONHOC ALTER TABLE KETQUA DROP FK_KETQUA_SINHVIEN
DROP TABLE SINHVIEN,Khoa,MONHOC,KETQUA